# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: windows-latest

    

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '14.17.3'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build dmk-wing
      run: npm run build:ci
    - name: Deploy to GitHub Pages of dmk-wing
      uses: crazy-max/ghaction-github-pages@v3
      with:
          GITHUB_TOKEN: ${{ REDMIND_DMK }}
          target_branch: gh-pages
          build_dir: dist/sakai-ng
